config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :contacts, only: [:new, :create]
  resources :opinions
  resources :company_data, only: [:edit, :update]
  resources :business_methods, only: [:new, :create, :update, :destroy, :show]
  resources :home_pages, only: [:edit, :update]
  resources :galleries, only: [:edit, :update, :show]
  resources :gallery_contents, only: [:create, :destroy]
  delete 'gallery_contents/:id' => 'gallery_contents#destroy', as: :delete_gallery
  delete 'users/:id'  => 'users#destroy', as: :admin_destroy_user
  get '/users'        => 'users#index'
  get '/contact'      => 'contacts#new'
  post '/'            => 'static_pages#event_cookies', as: :cookies_deploy

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140, minimum: 40 }
  validates :user_id, presence: true

  def to_param
    "#{id}-#{content.first(25).parameterize}"
  end

end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :show, :new]
  before_action :correct_admin, only: [:destroy, :index, :update, :edit]

  def new
    if current_user.opinion
      redirect_to request.referrer || root_path
      flash[:notice] = 'Użytkownik posiada już opinię.'
    end

    @opinion = Opinion.new

  end

  def update
    @opinion = Opinion.find(params[:id])
    if @opinion.update_attributes(opinion_params)
      redirect_to request.referrer
    else
      redirect_to request.referrer
      flash[:notice] = 'Nie udało się edytować.'
    end
  end

  def edit
    @opinion = Opinion.find(params[:id])
  end

  def create
    @opinion = current_user.build_opinion(opinion_params)
    if @opinion.save
      flash[:notice] = "Przesłano opinię, dziękujemy."
      redirect_to root_path
    else
      flash[:notice] = "Nie udało się przesłać opini."
      render 'new'
    end
  end

  def destroy
    @opinion = Opinion.find(params[:id]).delete
    redirect_to request.referrer || root_path
  end

  def show
  end

  def index
    @opinions = Opinion.paginate(:page => params[:page], :per_page => 10)
  end

  private

  def opinion_params
    params.require(:opinion).permit(:content)
  end

end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.erb
<td></td>
<td>
  <p><strong>Edycja opini:</strong></p>

  <%= simple_form_for @opinion do |form| %>
      <%= form.input :content, as: :text, input_html: { :value => @opinion.content, minleangth: 50, maxlength: 140 }, label: 'Treść:', hint: 'Znaki Minimum: 50 Maximum: 140', required: false %>

      <%= form.button :submit, 'Zmień opinię' %>
  <% end %>

</td>
<td></td>

app/views/opinions/edit.js.erb
$('#<%=@opinion.id%>_edit_slide').toggle();
$('#<%=@opinion.id%>_edit_slide').html("<%= j render 'form'  %>");

app/views/opinions/index.html.erb
<% title 'Indeks Opinii' %>
<% description 'Wylewki Mixokretem Tynki Agregatem Posadzki Przemysłowe na terenie: Połaniec, Staszów, Osiek i inne. Najlepsza jakość i rozsądne ceny!' %>
<% keywords 'Krzysztof Borkowski Wylewki Tynki Posadzki Połaniec Staszów Mielec Tarnobrzeg Osiek Wylewka Tynk Posadzka Agregatem Mixokretem Przemysłowa Firma Budowlana Budownictwo Remont Beton Jakość Cena Facebook'  %>

<div class="container" id="back_other">
  <div class="row" id="row_next">
    <div class="col-sm-offset-1 col-sm-10 col-lg-offset-1 col-lg-10">

          <div class="table-responsive">
              <table class="table table-hover">

                <tr>
                  <th>Opinion_id</th>
                  <th>Treść</th>
                  <th>Użytkownik / id</th>
                </tr>

                <% @opinions.each do |opinion| %>

                    <tr>
                      <td><%= opinion.id %></td>
                      <td><%= opinion.content %> &nbsp; <%= link_to '<i class="fa fa-times"></i>'.html_safe, opinion, :method => :delete %> &nbsp;
                        <%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_opinion_path(opinion), remote: true %> </td>
                      <td><abbr title=" <%= opinion.user.email %> "><%= opinion.user.name %> </abbr> / <b><%= opinion.user.id %></b></td>
                    </tr>
                    <tr id="<%=opinion.id%>_edit_slide" style="display: none"></tr>

                <% end %>


              </table>
          </div>

      <%= will_paginate @opinions, renderer: BootstrapPagination::Rails, :previous_label => t("Wstecz"), :next_label => t("Dalej") %>


    </div>
  </div>
</div>

app/views/opinions/new.html.erb
<% title 'Napisz opinię o nas' %>
<% description 'Wylewki Mixokretem Tynki Agregatem Posadzki Przemysłowe na terenie: Połaniec, Staszów, Osiek i inne. Najlepsza jakość i rozsądne ceny!' %>
<% keywords 'Krzysztof Borkowski Wylewki Tynki Posadzki Połaniec Staszów Mielec Tarnobrzeg Osiek Wylewka Tynk Posadzka Agregatem Mixokretem Przemysłowa Firma Budowlana Budownictwo Remont Beton Jakość Cena Facebook'  %>

<div class="container" id="back_other">
  <div class="row" id="row_next">
    <div class="col-sm-offset-1 col-sm-10 col-lg-offset-1 col-lg-10">

      <h2>Napisz Opinię o nas</h2>

      <%= simple_form_for @opinion do |opinion| %>

          <%= opinion.input :content, required: true, label: 'Treść:', input_html: { minleangth: 40, maxlength: 140  }, hint: 'Ilość znaków: 50 minimum, 140 maksimum' %>

          <%= opinion.button :submit, 'Prześlij opinię' %>

      <% end %>

    </div>
  </div>
</div>

app/views/opinions/show.html.erb
<% title 'Indeks Opinii' %>
<% description 'Wylewki Mixokretem Tynki Agregatem Posadzki Przemysłowe na terenie: Połaniec, Staszów, Osiek i inne. Najlepsza jakość i rozsądne ceny!' %>
<% keywords 'Krzysztof Borkowski Wylewki Tynki Posadzki Połaniec Staszów Mielec Tarnobrzeg Osiek Wylewka Tynk Posadzka Agregatem Mixokretem Przemysłowa Firma Budowlana Budownictwo Remont Beton Jakość Cena Facebook'  %>

<div class="container" id="back_other">
  <div class="row" id="row_next">
    <div class="col-sm-offset-1 col-sm-10 col-lg-offset-1 col-lg-10">

      <h2>Twoja Opinia</h2>

      <br>

      <div class="row">

      <div class="jumbotron" style="box-shadow: 5px 5px 11px 0">

        <% if current_user.opinion.content =~ /^(")+(.)+(")$/i %>
            <h4><i><%= current_user.opinion.content %></i></h4>
        <% else %>
            <h4><i><%= '"'+current_user.opinion.content+'"' %></i></h4>
        <% end %>

      </div>

      </div>

      <p>
        W celu edycji opinii, prosimy skontaktować się z nami poprzez formularz dostępny poniżej:

        <br><br>

        <%= link_to "Formularz kontaktowy", contact_path + '#contact_link' %>
      </p>

    </div>
  </div>
</div>