config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :contacts, only: [:new, :create]
  resources :opinions
  resources :company_data, only: [:edit, :update]
  resources :business_methods, only: [:new, :create, :update, :destroy, :show]
  resources :home_pages, only: [:edit, :update]
  resources :galleries, only: [:edit, :update, :show]
  resources :gallery_contents, only: [:create, :destroy]
  delete 'gallery_contents/:id' => 'gallery_contents#destroy', as: :delete_gallery
  delete 'users/:id'  => 'users#destroy', as: :admin_destroy_user
  get '/users'        => 'users#index'
  get '/contact'      => 'contacts#new'
  post '/'            => 'static_pages#event_cookies', as: :cookies_deploy

end

app/models/business_method.rb
class BusinessMethod < ActiveRecord::Base
  validates :title, presence: true
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }
  default_scope -> { order('id ASC') }

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/company_datum.rb
class CompanyDatum < ActiveRecord::Base
  validates :title, presence: true
  validates :email, format: Devise::email_regexp
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }
  default_scope -> { order('id ASC') }
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Formularz kontaktowy",
        :to => "borkowskiwylewki@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true
  validates :title_footer, presence: true
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }

  def to_param
    "#{id}-#{title.first(25).parameterize}"
  end
end

app/models/gallery_content.rb
class GalleryContent < ActiveRecord::Base
  has_attached_file :image, validates: true,styles: {
      thumb:  '100x100>',
      square: '150x150#',
      medium: '500x500>'
  }
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  default_scope -> { order('created_at DESC') }

end

app/models/home_page.rb
class HomePage < ActiveRecord::Base
  validates :title, presence: true
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }
  default_scope -> { order('id ASC') }

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140, minimum: 40 }
  validates :user_id, presence: true

  def to_param
    "#{id}-#{content.first(25).parameterize}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :opinion, :dependent => :destroy
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    @com_data = CompanyDatum.find(1)
  end

  def create
    @com_data = CompanyDatum.find(1)
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:notice] = 'Dziękujemy za wiadomość. Skontaktujemy się z Tobą najszybciej jak to tylko możliwe.'
      redirect_to root_path
    else
      flash[:notice] = 'Nie można wysłać wiadomości.'
      render :new
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :correct_admin, only: [:edit, :update]
  before_action :correct_gallery

  def edit
    @gal_cont = GalleryContent.new
  end

  def update
    if @gallery.update_attributes(gallery_params)
      flash[:notice] = 'Zaktualizowano dane.'
      redirect_to request.referrer
    else
      flash[:notice] = 'Nieudana aktualizacja danych.'
      render 'edit'
    end
  end

  def show
  end

  def correct_gallery
    @gallery = Gallery.find(1)
  end

  private

  def gallery_params
    params.require(:gallery).permit(:title, :title_footer,
               :met_title, :met_description, :met_keywords, :content_top, :content_bottom)
  end

end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  before_action :correct_admin

  def edit
    @home_p = HomePage.find(1)
  end

  def update
    @home_p = HomePage.find(1)
    if @home_p.update_attributes(home_params)
      flash[:notice]= 'Dokonano edycji'
      redirect_to request.referrer
    else
      render 'edit'
      flash[:notice]= 'Nieudana próba edycji'
    end
  end

  private

  def home_params
    params.require(:home_page).permit(:title, :content,
                                      :met_title, :met_description, :met_keywords, :carousel)
  end

end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :show, :new]
  before_action :correct_admin, only: [:destroy, :index, :update, :edit]

  def new
    if current_user.opinion
      redirect_to request.referrer || root_path
      flash[:notice] = 'Użytkownik posiada już opinię.'
    end

    @opinion = Opinion.new

  end

  def update
    @opinion = Opinion.find(params[:id])
    if @opinion.update_attributes(opinion_params)
      redirect_to request.referrer
    else
      redirect_to request.referrer
      flash[:notice] = 'Nie udało się edytować.'
    end
  end

  def edit
    @opinion = Opinion.find(params[:id])
  end

  def create
    @opinion = current_user.build_opinion(opinion_params)
    if @opinion.save
      flash[:notice] = "Przesłano opinię, dziękujemy."
      redirect_to root_path
    else
      flash[:notice] = "Nie udało się przesłać opini."
      render 'new'
    end
  end

  def destroy
    @opinion = Opinion.find(params[:id]).delete
    redirect_to request.referrer || root_path
  end

  def show
  end

  def index
    @opinions = Opinion.paginate(:page => params[:page], :per_page => 10)
  end

  private

  def opinion_params
    params.require(:opinion).permit(:content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
 before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
     if current_user.admin?
       if
          cookies[:opin_numb].to_i < Opinion.count
          flash[:notice] = 'Dodano nową opinię.'
          cookies.delete(:opin_numb)
       end
     end
   end

  # DELETE /resource/sign_out
   def destroy
     if current_user.admin?
       cookies[:opin_numb] = Opinion.count
     end
     super
   end

   protected

  # You can put the params you want to permit in the empty array.
   def configure_sign_in_params
     devise_parameter_sanitizer.for(:sign_in) << :attribute
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_admin

  def index
    @users = User.paginate(:page => params[:page], :per_page => 15)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to request.referrer || root_url, notice: "Użytkownik usunięty."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def opinion_id_cont
    int_opin = []
    Opinion.all.each { |x| int_opin << x.id.to_i }
    @rand_opin = Opinion.find(int_opin.sample)
    @rand_opin_cont = @rand_opin.content
  end

  def show_user
    @rand_opin.user.name
  end

end

app/helpers/business_methods_helper.rb
module BusinessMethodsHelper
end

app/helpers/company_data_helper.rb
module CompanyDataHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_contents_helper.rb
module GalleryContentsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/new.html.erb
<% title @com_data.met_title %>
<% description @com_data.met_description %>
<% keywords @com_data.met_keywords %>

<div class="container" id="back_other">

      <%= CompanyDatum.find(1).content.html_safe %>

  <div class="row" id="row_next">
    <div class="col-sm-offset-1 col-sm-10 col-lg-offset-1 col-lg-10">

      <h2 id="contact_link">Wyślij wiadomość do nas</h2>

      <br>

      <%= simple_form_for @contact do |f| %>
          <%= user_signed_in? ? (f.input :name, :required => true, :label => 'Imię', input_html: { :value => current_user.name }) : (f.input :name, :required => true, :label => 'Imię') %>
          <%= user_signed_in? ? (f.input :email, :required => true, input_html: { :value => current_user.email }) : (f.input :email, :required => true) %>
          <%= f.input :message, :as => :text, :required => true, label: 'Wiadomość' %>
          <div class= "hidden">
          <%= f.input :nickname, :hint => 'Zostaw te pole puste!' %>
          </div>
          <div>
            <br>
          <%= f.button :submit, 'Wyślij wiadomość', :class=> "btn btn-primary" %>
          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<% title 'Indeks Użytkowników' %>
<% description 'Wylewki Mixokretem Tynki Agregatem Posadzki Przemysłowe na terenie: Połaniec, Staszów, Osiek i inne. Najlepsza jakość i rozsądne ceny!' %>
<% keywords 'Krzysztof Borkowski Wylewki Tynki Posadzki Połaniec Staszów Mielec Tarnobrzeg Osiek Wylewka Tynk Posadzka Agregatem Mixokretem Przemysłowa Firma Budowlana Budownictwo Remont Beton Jakość Cena Facebook'  %>

<div class="container" id="back_other">

  <div class="row" id="row_next">
    <div class="col-md-offset-1 col-md-10">

      <div class="table-responsive">
        <table class="table table-hover">

          <tr>
            <th>Użytkownik_id</th>
            <th>Imię</th>
            <th>Email</th>
            <th>Usunięcie</th>
          </tr>
          <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.email %>
                <td><%= link_to '<i class="fa fa-times"></i>'.html_safe, admin_destroy_user_path(user), :method => :delete %></td>
              </tr>
          <% end %>

        </table>
      </div>

      <%= will_paginate @users, renderer: BootstrapPagination::Rails, :previous_label => t("Wstecz"), :next_label => t("Dalej") %>

    </div>
  </div>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Logowanie", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Zarejestruj się", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Zapomniałeś hasła?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Nie otrzymałeś wiadomości potwierdzającej?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Nie otrzymałeś wiadomości aktywacyjnej?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>