config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :contacts, only: [:new, :create]
  resources :opinions
  resources :company_data, only: [:edit, :update]
  resources :business_methods, only: [:new, :create, :update, :destroy, :show]
  resources :home_pages, only: [:edit, :update]
  resources :galleries, only: [:edit, :update, :show]
  resources :gallery_contents, only: [:create, :destroy]
  delete 'gallery_contents/:id' => 'gallery_contents#destroy', as: :delete_gallery
  delete 'users/:id'  => 'users#destroy', as: :admin_destroy_user
  get '/users'        => 'users#index'
  get '/contact'      => 'contacts#new'
  post '/'            => 'static_pages#event_cookies', as: :cookies_deploy

end

app/models/business_method.rb
class BusinessMethod < ActiveRecord::Base
  validates :title, presence: true
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }
  default_scope -> { order('id ASC') }

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/company_datum.rb
class CompanyDatum < ActiveRecord::Base
  validates :title, presence: true
  validates :email, format: Devise::email_regexp
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }
  default_scope -> { order('id ASC') }
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Formularz kontaktowy",
        :to => "borkowskiwylewki@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true
  validates :title_footer, presence: true
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }

  def to_param
    "#{id}-#{title.first(25).parameterize}"
  end
end

app/models/gallery_content.rb
class GalleryContent < ActiveRecord::Base
  has_attached_file :image, validates: true,styles: {
      thumb:  '100x100>',
      square: '150x150#',
      medium: '500x500>'
  }
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  default_scope -> { order('created_at DESC') }

end

app/models/home_page.rb
class HomePage < ActiveRecord::Base
  validates :title, presence: true
  validates :met_title, length: { maximum: 70 }
  validates :met_description, length: { maximum: 160 }
  validates :met_keywords, length: { maximum: 255 }
  default_scope -> { order('id ASC') }

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140, minimum: 40 }
  validates :user_id, presence: true

  def to_param
    "#{id}-#{content.first(25).parameterize}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :opinion, :dependent => :destroy
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    @com_data = CompanyDatum.find(1)
  end

  def create
    @com_data = CompanyDatum.find(1)
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:notice] = 'Dziękujemy za wiadomość. Skontaktujemy się z Tobą najszybciej jak to tylko możliwe.'
      redirect_to root_path
    else
      flash[:notice] = 'Nie można wysłać wiadomości.'
      render :new
    end
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :show, :new]
  before_action :correct_admin, only: [:destroy, :index, :update, :edit]

  def new
    if current_user.opinion
      redirect_to request.referrer || root_path
      flash[:notice] = 'Użytkownik posiada już opinię.'
    end

    @opinion = Opinion.new

  end

  def update
    @opinion = Opinion.find(params[:id])
    if @opinion.update_attributes(opinion_params)
      redirect_to request.referrer
    else
      redirect_to request.referrer
      flash[:notice] = 'Nie udało się edytować.'
    end
  end

  def edit
    @opinion = Opinion.find(params[:id])
  end

  def create
    @opinion = current_user.build_opinion(opinion_params)
    if @opinion.save
      flash[:notice] = "Przesłano opinię, dziękujemy."
      redirect_to root_path
    else
      flash[:notice] = "Nie udało się przesłać opini."
      render 'new'
    end
  end

  def destroy
    @opinion = Opinion.find(params[:id]).delete
    redirect_to request.referrer || root_path
  end

  def show
  end

  def index
    @opinions = Opinion.paginate(:page => params[:page], :per_page => 10)
  end

  private

  def opinion_params
    params.require(:opinion).permit(:content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
 before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
     if current_user.admin?
       if
          cookies[:opin_numb].to_i < Opinion.count
          flash[:notice] = 'Dodano nową opinię.'
          cookies.delete(:opin_numb)
       end
     end
   end

  # DELETE /resource/sign_out
   def destroy
     if current_user.admin?
       cookies[:opin_numb] = Opinion.count
     end
     super
   end

   protected

  # You can put the params you want to permit in the empty array.
   def configure_sign_in_params
     devise_parameter_sanitizer.for(:sign_in) << :attribute
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_admin

  def index
    @users = User.paginate(:page => params[:page], :per_page => 15)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to request.referrer || root_url, notice: "Użytkownik usunięty."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def opinion_id_cont
    int_opin = []
    Opinion.all.each { |x| int_opin << x.id.to_i }
    @rand_opin = Opinion.find(int_opin.sample)
    @rand_opin_cont = @rand_opin.content
  end

  def show_user
    @rand_opin.user.name
  end

end

app/helpers/business_methods_helper.rb
module BusinessMethodsHelper
end

app/helpers/company_data_helper.rb
module CompanyDataHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_contents_helper.rb
module GalleryContentsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>

    <div class="container" id="back2nd" style='margin-top: <%= yield(:footer_top) %>'>

      <% if Opinion.count > 0 %>

      <div class="row" id="title_opinion">
        <div class="col-md-10 col-md-offset-1">
          <h4 style="color: #C1C1C1"><em>Opinie o nas:</em></h4>
      </div>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">

          <div class="owl-carousel_foot owl-theme" id="owl-slide2">

            <% Opinion.all.each do %>

                <div class="item"> <blockquote style="border-top-left-radius: 5px"> <p><%= opinion_id_cont %></p> <footer><%= show_user %></footer></blockquote> </div>
                <div class="item"> <blockquote style="border-top-right-radius: 5px" class="blockquote-reverse"> <p><%= opinion_id_cont %></p> <footer><%= show_user %></footer></blockquote> </div>

            <% end %>
          </div>

        </div>
      </div>

      <% end %>

      <div class="row" id="row_foot">
        <div class="col-xs-12 col-md-6">
          <div class="row" id="row_f_left">
            <div class="col-xs-6 col-md-5 col-md-offset-1" style="padding-right: 0">
              <h4>
                  <ul style="padding-left: 0">
                    <li><%= link_to 'Strona Główna', root_path %></li>
                    <% BusinessMethod.all.each do |method| %>
                        <li><%= link_to method.title, business_method_path(method) %></li>
                    <% end %>
                    <li><%= link_to Gallery.find(1).title_footer, gallery_path(Gallery.find(1)) %></li>
                    <li><%= link_to 'Napisz do nas', contact_path + '#contact_link' %></li>
                  </ul>
              </h4>
            </div>

            <div class="col-xs-5 col-md-5" style="padding-right:0">
              <h4>

                <ul style="padding-left: 0">
                  <li><%= link_to "Zarejestruj się", new_user_registration_path %></li>
                  <li><%= link_to "Panel logowania", new_user_session_path %></li>
                  <li><%= link_to "Napisz opinię o nas", new_opinion_path %></li>
                </ul>

                <div style="letter-spacing: 8px; padding-left: 10px">

                  <a href='http://www.borkowski_wylewki_tynki.oferteo.pl/' target='blank'>
                    <img src='http://www.oferteo.pl/images/buttons/oferteo_m3.gif?customerId=135558' border='0' alt='Zobacz Krzysztof Borkowski "Tynki agregatem, Wylewki mixokretem, Posadzki przemyslowe" na Oferteo.pl' title='Krzysztof Borkowski "Tynki agregatem, Wylewki mixokretem, Posadzki przemyslowe" w Oferteo.pl'/>
                  </a><%= link_to '<i class="fa fa-facebook-square fa-2x"></i>'.html_safe, 'https://www.facebook.com/BorkowskiWylewki?fref=ts', style: 'color:#C1C1C1' %><%= link_to '<i class="fa fa-google-plus-square fa-2x"></i>'.html_safe, 'https://plus.google.com/117537649942138441187/posts', style: 'color:#C1C1C1' %>

                </div>

                <br>

              </h4>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-xs-12">
            <hr class='row hidden-lg hidden-md'>


                <div class="col-xs-offset-1 col-xs-4 col-md-5" style="margin-left: 10px">
                  <h4>Adres firmy:<br><br></h4>
                  <address>
                    <h5>
                      <%= CompanyDatum.find(1).name.html_safe %><br><br>
                      <%= CompanyDatum.find(1).address.html_safe %><br>

                    </h5>
                  </address>
                </div>

                <div class="col-xs-5 col-md-5">

                    <h4>Informacje kontaktowe:<br><br></h4>
                    <address>
                      <h5>

                        <%= link_to CompanyDatum.find(1).email.html_safe, 'mailto:' + CompanyDatum.find(1).email, style: 'text-decoration:none; color:#C1C1C1; font-weight: bold' %> <br><br>
                        <%= CompanyDatum.find(1).mob_phone.html_safe %><br>
                        <%= CompanyDatum.find(1).phone.html_safe %><br>

                      </h5>
                    </address>
                </div>

        </div>
      </div>

      <div class="row" id="author">
        Copyright &copy; Kamil Tarnowski
      </div>
    </div>

</footer>

app/views/layouts/_header.html.erb
<header>

  <div class='container' id="back_logo">
    <%= link_to image_tag('https://s3.eu-central-1.amazonaws.com/borkowski/layout/logo_main.jpg', alt: 'Logo Krzysztof Borkowski', id: 'logo_image'), root_path %>
  </div>
  <nav class="navbar navbar-inverse" style="box-shadow: <%= yield(:header_box) %>">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand hidden-lg hidden-md hidden-sm" href=<%= root_path %> >Krzysztof Borkowski</a>
      </div>
      <div class="collapse navbar-collapse" id="Navbar">
        <ul class="nav navbar-nav">
          <li class=" <%= 'active' if current_page?(root_path) %> "><%= link_to '<i class="fa fa-home"></i>'.html_safe + HomePage.find(1).title, root_path %></li>

          <li class="dropdown <% BusinessMethod.all.each do |method| %>
                                <%= 'active' if current_page?(business_method_path(method)) %>
                              <% end %>">
            <a class="dropdown-toggle " data-toggle="dropdown" href="">Zakres działalności<i class="fa fa-caret-down"></i></a>

            <ul class="dropdown-menu"">
            <% BusinessMethod.all.each do |method| %>
                <li class=" <%='active' if current_page?(business_method_path(method)) %> "><a href=" <%= business_method_path(method) %> "><%= method.title.html_safe %></a> </li>
            <% end %>
            </ul>

          </li>

          <li class="<%='active' if current_page?(gallery_path(Gallery.find(1))) %>"><a href=" <%= gallery_path(Gallery.find(1)) %> "><i class="fa fa-picture-o"></i><%= Gallery.find(1).title %></a></li>
          <li class=" <%='active' if current_page?(contact_path) %> "><a href=" <%= contact_path %> "><i class="fa fa-envelope"></i><%= CompanyDatum.find(1).title %></a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
              <% if current_user.opinion %>
                  <li class=" <%= 'active' if current_page?(current_user.opinion) %> "> <%= link_to '<i class="fa fa-comment"></i>Opinia'.html_safe, current_user.opinion %></li>
              <% end %>
              <% if current_user.opinion.nil? %>
                  <li class=" <%= 'active' if current_page?(new_opinion_path) %> "> <%= link_to '<i class="fa fa-comment-o"></i>Nowa opinia'.html_safe, new_opinion_path %></li>
              <% end %>
              <% if current_user.admin? %>
                  <li class="dropdown">
                  <li class=" <%='active' if current_page?(users_path) || current_page?(opinions_path) %> "><a class="dropdown-toggle" data-toggle="dropdown" href>Panel Admina<i class="fa fa-caret-square-o-down"></i></a>
                    <ul class="dropdown-menu">
                      <li class=" <%='active' if current_page?(users_path) %> "><%= link_to 'Użytkownicy', users_path %></li>
                      <li class=" <%='active' if current_page?(opinions_path) %> "><%= link_to 'Opinie', opinions_path %></li>
                      <li class="<%= 'active' if current_page?(new_business_method_path) %>"><%= link_to 'Napisz nową metodę', new_business_method_path %></li>
                      <li class="<%= 'active' if current_page?(edit_home_page_path(HomePage.find(1))) %>"><%= link_to 'Strona główna', edit_home_page_path(HomePage.find(1)) %></li>
                      <li class="<%= 'active' if current_page?(edit_company_datum_path(CompanyDatum.find(1))) %>"><%= link_to 'Dane firmy', edit_company_datum_path(CompanyDatum.find(1)) %></li>
                      <li class=" <%='active' if current_page?(edit_gallery_path(Gallery.find(1))) %> "><%= link_to 'Edycja Galerii', edit_gallery_path(Gallery.find(1)) %></li>
                    </ul>
                  </li>
              <% end %>
              <li class="dropdown">
              <li class=" <%='active' if current_page?(edit_user_registration_path) %> "><a class="dropdown-toggle" data-toggle="dropdown" href>Konto użytkownika<i class="fa fa-caret-square-o-down"></i></a>
                <ul class="dropdown-menu">
                  <li class=" <%='active' if current_page?(edit_user_registration_path) %> "> <%= link_to '<i class="fa fa-pencil fa-fw"></i>Edycja'.html_safe, edit_user_registration_path %></li>
                  <li> <%= link_to '<i class="fa fa-sign-out"></i>Wyloguj mnie'.html_safe, destroy_user_session_path , :method => :delete %> </li>
                </ul>
              </li>
          <% else %>
              <li class=" <%='active' if current_page?(new_user_registration_path) %> "><a href=" <%= new_user_registration_path %> "><i class="fa fa-user fa-fw"></i>Rejestracja</a></li>
              <li class=" <%='active' if current_page?(new_user_session_path) %> "><a href=" <%= new_user_session_path %> "><i class="fa fa-sign-in"></i>Logowanie</a></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= display_meta_tags :site => 'Krzysztof Borkowski' %>

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render 'layouts/shim' %>
  <link rel="shortcut icon" href="/favicon.ico?v=2" />
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>
<body>

    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <div id="fb-root"></div>
    <div id="facebook-container">

      <div style="display: inline"><i class="fa fa-facebook-square fa-5x" style="color: #3b5998; padding-top: 6px"></i></div>
      <div style="display: inline" class="fb-like" data-href="https://www.facebook.com/BorkowskiWylewki?fref=ts" data-width="300" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

    </div>
    <%= debug(params) if Rails.env.development? %>
    <div id='button_up'><i class="fa fa-angle-double-up fa-3x"></i></div>

    <% unless cookies[:maintain_borkowski] == 'TRUE' %>

        <div id="cookies"> Korzystając z serwisu wyrażasz zgodę na wykorzystanie przez nas plików cookies, w celu zapewnienia Tobie wygody podczas przeglądania stron serwisu.
          <div style="display:inline-block;">
            <%= button_to 'Zamknij', cookies_deploy_path, remote: true, class: "button button-default", style: 'text-align: right'  %>
          </div>
        </div>

    <% end %>

    <script>

        <% flash.each do |key, value| %>
        <%= add_gritter(value, flash[key], :image => :notice, :title => 'Komunikat:', nodom_wrap: true) %>
        <% end %>

    </script>

</body>
</html>

app/views/shared/_header.html.erb
<div class='container'>
  <div class="row" id="logo">
    <div class="col-md-6">
      <%= link_to image_tag('cinqueterre.jpg', alt: 'Logo',
                            style: 'width:30%; high:30px; border-radius:4px' ), root_path %>
    </div>
  </div>
</div>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <<a class="navbar-brand hidden-lg hidden-md" href="./">Borkowski Wylewki</a>
    </div>
    <div class="collapse navbar-collapse" id="Navbar">
        <ul class="nav navbar-nav">
          <li><%= link_to "Start", root_path %></li>
          <li class="dropdown">
          <li><a class='dropdown-toggle' data-toggle="dropdown" href="#">Wykorzystywane metody
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Metoda Pierwsza</a> </li>
              <li><a href="#">Metoda Druga</a> </li>
              <li><a href="#">Metoda Trzecia</a> </li>
            </ul>
          </li>
          <li><a href="#">Realizacje</a></li>
          <li><a href="#">Kontakt</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><span class="glyphicon glyphicon-user"></span>Rejestracja</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Logowanie</a></li>
        </ul>
      </div>
    </div>
</nav>